### ISSUE TITLE
Posted orders gets market mixed up

### ISSUE THREAD

**Issue by bjornreppen** [MiraiEx/trade-api-sdk#4]
Add a bid for ADA:
```javascript
 MiraiEx.createOrder("ADANOK", "bid", 19.239219999999996, 5.197715915717998)
```
Data being posted using axios inside createOrder API function
```javascript
{
    price: '19.239219999999996',
    amount: '5.197715915717998',
    market: 'ADANOK',
    type: 'bid'
}
```
All seems, good but the order showing up in the web UI after running the code, has market changed to BTCNOK:

![bilde](https://user-images.githubusercontent.com/281359/134764739-142a3c63-87c8-4a33-b926-20e93fb9bb41.png)

**Comment by ktpx** [comment]
I believe the API history/order function has a bug (i reported this), it seems to interchange ADANOK and BTCNOK in the market field (probably just a index lookup issue).   I get the same "problem" on my api calls.

**Comment by ktpx** [comment]
This is fixed, btw.

**Comment by bjornreppen** [comment]
Thanks @ktpx
